name: Features Packages

on: 
  push:
    branches: 
      - "main"
    paths:
      - ".github/workflows/packages.yml"
      - "types/**"

jobs:
  build-publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          - feature: workloads-types
            dir: types
            

    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      working-directory: ${{ matrix.dir }}
      run: npm install --workspaces=false
    - name: Build
      working-directory: ${{ matrix.dir }}
      run: npm run build
    - name: Set up Node.js for GPR
      uses: actions/setup-node@v3
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: Publish package to NPM
      working-directory: ${{ matrix.dir }}
      run: npm publish --access public
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}